### ISSUE TITLE
Add Documentation for Python

### ISSUE THREAD

**Issue by jchristgit** [SpecialKids/HackBoat#11]
Add a `!doc python <keyword>` Command to search the Python documentation for the given term. <https://docs.python.org/3/>

**Comment by cronokirby** [comment]
I suggest !pydoc instead, for a few reasons, the first being that the way this command will get docs is completely different from the way the elixir command will, since the elixir one can search locally for info.
!exdoc; !pydoc; !cppdoc seem like a decent trio, and allow us to seperate concerns when writing the library.
